### ISSUE TITLE
tabular data/ noisy instances 

### ISSUE THREAD

**Issue by nazaretl** [deu30303/RUC#14]
Hi,
thanks for sharing your implementation. I have two questions about it:

1.	Does it also work on tabular data?
2.	Is it possible to identify the noisy instances (return the noisy IDs or the clean set).

Thanks!

**Comment by deu30303** [comment]
Hi, thank you for your interest in our work!

1. Since our model targets the vision data set, I cannot guarantee that it will work well in the tablet data set. 
You have to replace each component to be applicable to the tabular data.   
2. You can get a noisy or clean instances idx from sampling function (ex, extract_hybrid, extract_metric, extract_confidence)

Thank you again for your interest.

**Comment by nazaretl** [comment]
many thanks!
